# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e5c00b5c39135aaef9dfe0470d37521f15ae2d25e2061705ceaaf41ff6d0cb9d0aeed9fcbabd6fe4f7fed59c09dcf59dfc384d1454caf95bcb1a105b6b67ae69

test:
  secret_key_base: bdf026a05850d1e0c74b6aec717e89d73984a3558cbfb7a30fcaf6e081625a9155cde8e59831b8ddbdfa56799a157cb8b8ef80fa44c986135137547379af3d91

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
